### ISSUE TITLE
软件商店 代理选型调研

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#127]
1. [nginxproxymanage api 调研](https://github.com/Websoft9/docker-library/issues/256)
2.  nginxproxy 调研
3. 其他相关
https://www.casaos.io/  家庭云服务器操作系统（实际上就是docker应用管理）
https://umbrel.com/ 家庭云服务器操作系统
https://github.com/meienberger/runtipi /家庭云服务器操作系统

**Comment by qiaofeng1227** [comment]
nginxproxy 调研结果：
1. 暂时没有找到可视化操作界面和api调用配置方法
2. 架构图
![image](https://user-images.githubusercontent.com/43192516/215258096-d8f9fd3c-955d-4a71-a3c7-47027b50a462.png)
3. 示例
- 后端服务docker容器添加环境变量
 a. VIRTUAL_HOST
 b. LETSENCRYPT_HOST
- nginx proxy内置应用docker-gen会通过docker api监听所有容器的启动和关闭,过滤出包含有环境变量VIRTUAL_HOST的容器
- 通过docker api获取docker inspect类似的信息,IP和PORT,使用预定义的模版生成nginx的配置文件
- 监听nginx的配置文件目录,重启nginx服务
```
version: '2'
services:
 nginx-proxy:
 container_name: nginx-proxy
 image: nginxproxy/nginx-proxy
 volumes:
 - ./certs:/etc/nginx/certs
 - ./vhost:/etc/nginx/vhost.d
 - ./html:/usr/share/nginx/html
 - /var/run/docker.sock:/tmp/docker.sock:ro
 environment:
 - TZ=Asia/Shanghai
 ports:
 - "80:80"
 - "443:443"
 restart: always
 nginx-proxy-acme:
 container_name: nginx-proxy-acme
 image: nginxproxy/acme-companion:2.2
 volumes:
 - ./certs:/etc/nginx/certs
 - ./vhost:/etc/nginx/vhost.d
 - ./html:/usr/share/nginx/html
 - ./acme:/etc/acme.sh
 - /var/run/docker.sock:/var/run/docker.sock:ro
 environment:
 - TZ=Asia/Shanghai
 - DEFAULT_EMAIL=ywe188@163.com
 - NGINX_PROXY_CONTAINER=nginx-proxy
 restart: always
 nginx-test-website-01:
 container_name: nginx-test-website-01
 image: nginx
 volumes:
 - ./html-01:/usr/share/nginx/html
 environment:
 - TZ=Asia/Shanghai
 - VIRTUAL_HOST=test01.linbangwang.com
 - VIRTUAL_PORT=80
 - LETSENCRYPT_HOST=test01.linbangwang.com
 - LETSENCRYPT_EMAIL=ywe188@163.com
 restart: always
 nginx-test-website-02:
 container_name: nginx-test-website-02
 image: nginx
 volumes:
 - ./html-02:/usr/share/nginx/html
 environment:
 - TZ=Asia/Shanghai
 - VIRTUAL_HOST=test02.linbangwang.com
 - VIRTUAL_PORT=80
 - LETSENCRYPT_HOST=test02.linbangwang.com
 - LETSENCRYPT_EMAIL=ywe188@163.com
 restart: always
networks:
 default:
 external:
 name: net-product
```
