### ISSUE TITLE
docker network connect  main app with attached app at role_preend

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#29]
**What type of your feature request?**  

e.g

```
docker network connect wordpress phpmyadmin
```

**Comment by qiaofeng1227** [comment]
```
[root@iZj6cgoqbf91ty26hvwelpZ discuzq]# docker-compose
-bash: docker-compose: command not found
[root@iZj6cgoqbf91ty26hvwelpZ discuzq]# docker compose down -v
[+] Running 4/5
 ⠿ Container discuzq       Removed                                                                                                                                                                                                                                      10.3s
 ⠿ Container discuzq-db    Removed                                                                                                                                                                                                                                       1.4s
 ⠿ Network discuzq         Error                                                                                                                                                                                                                                         0.0s
 ⠿ Volume discuzq_discuzq  Removed                                                                                                                                                                                                                                       0.9s
 ⠿ Volume discuzq_mysql    Removed                                                                                                                                                                                                                                       0.9s
failed to remove network discuzq: Error response from daemon: error while removing network: network discuzq id 92bfc254c46db95ee2f9709d50e98659bc2e6eb8c2cebc86965018234d30f01f has active endpoints
[root@iZj6cgoqbf91ty26hvwelpZ discuzq]# docker ps
CONTAINER ID   IMAGE               COMMAND                  CREATED         STATUS         PORTS                                   NAMES
1a901a3403cb   phpmyadmin:latest   "/docker-entrypoint.…"   9 minutes ago   Up 7 minutes   0.0.0.0:9090->80/tcp, :::9090->80/tcp   phpmyadmin
[root@iZj6cgoqbf91ty26hvwelpZ discuzq]# 

```

**Comment by qiaofeng1227** [comment]
link
```
# image:https://hub.docker.com/_/phpmyadmin
# db container for test

version: "3.8"
services:
  phpmyadmin:
      image: phpmyadmin:$APP_VERSION
      container_name: $APP_NAME
      environment:
       - PMA_ARBITRARY=1
       - PMA_ABSOLUTE_URI=$APP_URL
       - UPLOAD_LIMIT=$APP_UPLOAD_LIMIT
      restart: always
      links:
        - "discuzq-db"
      ports:
       - ${APP_PORT}:80
[root@iZj6cgoqbf91ty513hr9ypZ phpmyadmin]# docker compose up -d
no such service: discuzq-db

```
