### ISSUE TITLE
Check pre.yml exists is not useful on mcloud

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#31]
change local path to remote path
``` 
   - name: Excute Preparation if have pre.yml
      block:
        - name: Check if pre.yml exists
          stat:
            path: roles/{{appname}}/tasks/pre.yml
          register: pre_exists
```

```
    - name: Excute Preparation if have pre.yml
      block:
        - name: Check if pre.yml exists
          uri:
            url: "https://github.com/Websoft9/StackHub/blob/main/apps/roles/{{appname}}/tasks/pre.yml"
            return_content: yes
          register: pre_exists
          failed_when: false
          
        - name: Excute pre.yml
          include_role:
            name: "{{appname}}"
            tasks_from: "pre"
          when: pre_exists.status is defined and pre_exists.status == 200
```
