### ISSUE TITLE
Optimize portainer  install wizard(create strong password, and sent to appmanage)

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#318]
portainer install wizard(create strong password) is processed at Websoft9 installation, suggest change this process to AppManage service  or they can process itself.

**Comment by qiaofeng1227** [comment]
Try to do it:
```
version: '3'
services:
  myservice:
    image: myservice:latest
    ports:
      - 8080:8080
    healthcheck:
      test:
        - "CMD-SHELL"
        - |
          command1
          command2
          command3
      interval: 30s
      timeout: 10s
      retries: 3
```
