### ISSUE TITLE
Optimize password setting at init_docker

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#33]
**What type of your feature request?**  

```
init_docker:
  metabase:
    admin_username: "admin@metabase.local"
    admin_password: "123456"
    db: mysql
    db_name: metabase
    db_username: root
    db_password: "123456"
```

精准匹配
