### ISSUE TITLE
Nginx proxy for Gitea

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#340]
**What type of your feature request?**  

Now, nginx proxy configure file need to add Public IP at root_url. How to remove Pulic IP and gitea can also access by Nginx

**Comment by qiaofeng1227** [comment]
```
  git:
    image: websoft9dev/git:$GIT_VERSION
    container_name: websoft9-git
    restart: always
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9001-9999:3000
    environment:
      - INSTALL_LOCK=true
      - DISABLE_SSH=true
      - RUN_MODE=prod
      - HTTP_PORT=3000
      - DISABLE_REGISTRATION=false
      - REQUIRE_SIGNIN_VIEW=false
      - ROOT_URL=/w9git/
      - STATIC_URL_PREFIX=/w9git
    labels:
      com.docker.compose.w9_http.port: 3000
```

**Comment by qiaofeng1227** [comment]
![image](https://github.com/Websoft9/websoft9/assets/43192516/6eb57ac7-30ee-4471-85c9-46b3c625af0e)
![image](https://github.com/Websoft9/websoft9/assets/43192516/b0261d1e-a1fb-4c68-b8eb-a396820b0564)

**Comment by qiaofeng1227** [comment]
```

  git:
    image: websoft9dev/git:$GIT_VERSION
    container_name: websoft9-git
    restart: always
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9001-9999:3000
    environment:
      - INSTALL_LOCK=true
      - DISABLE_SSH=true
      - RUN_MODE=prod
      - HTTP_PORT=3000
      - DISABLE_REGISTRATION=false
      - REQUIRE_SIGNIN_VIEW=false
      - ROOT_URL=http://REAL_HOST_REPLACE/w9git/
     ```
