### ISSUE TITLE
websoft9-apphub address changed

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#384]
when restart docker, websoft9-apphub address changed, cockpit call apphub api error.

**Comment by qiaofeng1227** [comment]
1. restart websoft9 service on finally
2. restart websoft9 service  after restart docker

**Comment by qiaofeng1227** [comment]
container network connect to host？

在 IPv4 地址体系中，有三个主要的地址段是被保留为私有地址的，这些地址只能在局域网内部使用，不用于 Internet，可以被任何人自由使用。这些私有地址范围包括：

10.0.0.0 - 10.255.255.255 (10.0.0.0/8)
172.16.0.0 - 172.31.255.255 (172.16.0.0/12)
192.168.0.0 - 192.168.255.255 (192.168.0.0/16)

方案：给容器 apphub 创建一个网络，并指定IP地址。另外，再指定一个外部网络

```
version: '3'
services:
  apphub:
    image: <your_image>
    networks:
      w9apphub:
        ipv4_address: 172.16.238.10  # 指定 IP 地址
networks:
  w9apphub:
    ipam:
      config:
        - subnet: 172.16.238.0/24
  default:
    name: websoft9
    external: true
```
