### ISSUE TITLE
Application backups

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#40]
**What type of your feature request?**  

容器的备份软件：

* 支持 volume 快照
* 支持第三方存储挂载
* 很好的 Docker 支持
* API 支持

**Comment by qiaofeng1227** [comment]
## 开源

- [Top 10 Free Backup software for Linux](https://computingforgeeks.com/top-10-free-backup-software-for-linux)
- [13 open source backup solutions](https://opensource.com/article/19/3/backup-solutions)
- [docker-volume-backup](https://github.com/offen/docker-volume-backup)
- [Docker Volume Snapshot Backup](https://manent-backup.com/docker-volume-snapshot-backup/)
- [8 CNCF Projects for Cloud-Native Persistent Storage](https://containerjournal.com/features/8-cncf-projects-for-cloud-native-persistent-storage/)
- 云原生对象存储软件
- https://kopia.io/
- https://velero.io/
- https://github.com/restic/restic
- http://minio.org.cn/
- https://rclone.org/

## 商业

* https://www.idrive.com/
* https://storagemadeeasy.com/

**Comment by qiaofeng1227** [comment]
1.  存储软件[minio](https://github.com/Websoft9/docker-library/blob/main/apps/minio/docker-compose.yml)
2.  [kopia](https://github.com/kopia/kopia/blob/master/tools/docker/docker-compose.yml)
```
version: '3.7'
services:
    kopia:
        image: kopia/kopia:latest
        hostname: Hostname
        container_name: Kopia
        restart: unless-stopped
        ports:
            - 51515:51515
        # Setup the server that provides the web gui
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure
            - --address=0.0.0.0:51515
            - --server-username=USERNAME
            - --server-password=SECRET_PASSWORD
        environment:
            # Set repository password
            KOPIA_PASSWORD: "SECRET"
            USER: "User"
        volumes:
            # Mount local folders needed by kopia
            - ./config:/app/config
            - ./cache:/app/cache
            - ./logs:/app/logs
            # Mount local folders to snapshot
            - ./data:/data:ro
            # Mount repository location
            - ./repository:/repository
            # Mount path for browsing mounted snaphots
            - ./tmp:/tmp:shared
```
3. [bacula demo](https://demo.bacularis.app/web),[bacula doc](https://bacularis.app/doc)

4. borgbackup
https://hub.docker.com/r/borgbackup/borg 官方四年没有更新了
epicsoft/borgbackup
https://gitlab.com/epicdocker/borgbackup/blob/master/README.md#License
找不到好的web容器
