### ISSUE TITLE
 build image in websoft9 when docker-compose.yml has build logic

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#541]
websoft9 cannot build image when compose has image and build，it will pull image from docker-hub:

```
services:
  php:
    container_name: ${W9_ID}
    image: $W9_REPO:$W9_VERSION
    build:
      context: .
      dockerfile: DOCKERFILE
      args:
         PHP_VERSION: $W9_VERSION
    restart: unless-stopped
    env_file: .env
```

Make it build image:

- [x] install app
- [x] recreate app
