### ISSUE TITLE
The installation script can not install  websoft9 on OracleLinux7.9

### ISSUE THREAD

**Issue by qiuf12** [Websoft9/websoft9#581]
**Describe the bug**

The installation script can not install docker or websoft9 on OracleLinux7.9

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] Ubuntu22.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiuf12** [comment]
wget -O install.sh https://websoft9.github.io/websoft9/install/install.sh && bash install.sh
<img width="529" alt="image" src="https://github.com/user-attachments/assets/efc1c03e-678d-40c1-a7d9-74e193afb7c8" />
<img width="959" alt="image" src="https://github.com/user-attachments/assets/3a711e20-82f3-487a-a14e-dc5c3eaa0435" />

**Comment by qiaofeng1227** [comment]
```
[root@iZbp1co6pzhfgxea15e5ddZ ~]# bash install.sh 
execute_mode=install

------ Welcome to install Websoft9, it will take 3-5 minutes ------

Your installation parameters are as follows: 
--version: latest
--port: 9000
--channel: release
--path: /data/websoft9/source
--apps: 
--mirrors: https://dockerhub.websoft9.com
--devto: 
--execute_mode: install

Your OS: 
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
Install from url: https://artifact.websoft9.com/release/websoft9
Stop Websoft9 Proxy and Cockpit service for reserve ports...
docker stop websoft9-proxy not need 
All ports are available

[Tools] -  Starting install necessary tool...
Cannot open: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm. Skipping.
Error: Nothing to do
Start to install git
https://yum.oracle.com/repo/OracleLinux/OL7/UEKR6/x86_64/repodata/d28506b65af74c8af6b67dd4172ef668baa20a98-primary.sqlite.bz2: [Errno 14] curl#7 - "Failed to connect to 2600:1417:4400:e81::2a7d: Network is unreachable"
Trying other mirror.
Start to install curl
Start to install wget
Start to install jq
Start to install bc
Start to install unzip
Start to install inotify-tools
Start to install yum-utils

[Download Source] -  Download Websoft9 source code from https://artifact.websoft9.com/release/websoft9/websoft9-latest.zip
--2025-01-09 08:24:54--  https://artifact.websoft9.com/release/websoft9/websoft9-latest.zip
Resolving artifact.websoft9.com (artifact.websoft9.com)... 104.21.38.184, 172.67.137.91, 2606:4700:3032::ac43:895b, ...
Connecting to artifact.websoft9.com (artifact.websoft9.com)|104.21.38.184|:443... connected.
Unable to establish SSL connection.


```

**Comment by qiaofeng1227** [comment]
https://www.17ce.com/
https://www.tcptest.cn/http

**Comment by chendelin1982** [comment]
Oracle Linux7 have `ol7_developer_EPEL` default and it have **inotify-tools** package, and below need fix
```
install_tools(){
    echo_prefix_tools=$'\n[Tools] - '
    echo "$echo_prefix_tools Starting install necessary tool..."

    if [ "$ID" = "rhel" ] || [ "$ID" = "ol" ]; then
        RHEL_VERSION=${VERSION_ID%%.*}
        sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-${RHEL_VERSION}.noarch.rpm >/dev/null
        if [ $? -ne 0 ]; then
            exit 1
        fi 
    elif [ "$ID" = "centos" ] || [ "$ID" = "rocky" ]; then
        sudo yum install -y "$repo_tools_yum" >/dev/null
        if [ $? -ne 0 ]; then
            exit 1
        fi 
```

Oracle Linux8 and Oracle Linux9 have epel?

**Comment by qiaofeng1227** [comment]
redhat does not have an epel source, and there is no way to find out how to install an epel source other than the method commented above

**Comment by qiaofeng1227** [comment]
磁盘扩展命令差异：
OracleLinux8,9
```
runcmd:
  - pvresize /dev/vda2
  - lvextend -l +100%FREE /dev/rootvg/rootlv
  - xfs_growfs /
```

OracleLinux 7（old）

```
runcmd:
  - [pvresize,/dev/vda2]
  - [lvextend,-l,+100%FREE,/dev/rootvg/rootlv]
  - [xfs_growfs,/dev/rootvg/rootlv]

```

**Comment by qiaofeng1227** [comment]
[阿里云导入镜像前需要配置网络](https://help.aliyun.com/zh/ecs/user-guide/cloud-marketplace-mirror-specification?spm=a2c4g.11186623.0.i0)

**Comment by qiaofeng1227** [comment]
DNS配置(和内部机一样)：
```
[root@iZbp1fulginzkis7kvrk8kZ tmp]# vim /etc/resolv.conf

# Generated by NetworkManager
nameserver 100.100.2.136
nameserver 100.100.2.138
```

**Comment by qiaofeng1227** [comment]
手动磁盘扩展成功，需要分区修复，需要交互
```
parted /dev/vda
print
fix
fix
print
resizepart 2 100%
quit
pvresize /dev/vda2
lvextend -l +100%FREE /dev/mapper/rootvg-rootlv
xfs_growfs /
```

**Comment by qiaofeng1227** [comment]
目前带cdn或者不带cdn的分多个时间测试多次，已经全部能下载。无法出现不能下载的现象。

**Comment by qiaofeng1227** [comment]
Oraclelinux7.9
```


# The top level settings are used as module
# and system configuration.

# A set of users which may be applied and/or used by various modules
# when a 'default' entry is found it will reference the 'default_user'
# from the distro configuration specified below
users:
   - default

user:
    name: root
    lock_passwd: False

# If this is set, 'root' will not be able to ssh in and they
# will get a message to login instead as the default $user
disable_root: false

# This will cause the set+update hostname module to not operate (if true)
preserve_hostname: false

manage_etc_hosts: localhost

datasource_list: [ AliYun ]

# Example datasource config
datasource:
    AliYun:
        support_xen: false
        timeout: 5
        max_wait: 300
#      metadata_urls: [ 'blah.com' ]

timezone: "Asia/Shanghai"

growpart:
  mode: auto
  devices: [/dev/vda2]
  ignore_growroot_disabled: false

runcmd:
  - [pvresize,/dev/vda2]
  - [lvextend,-l,+100%FREE,/dev/rootvg/rootlv]
  - [xfs_growfs,/dev/rootvg/rootlv]
  
# The modules that run in the 'init' stage
cloud_init_modules:
 - migrator
 - source-address
 - pip-source
 - seed_random
 - bootcmd
 - write-files
 - [ growpart, once-per-instance ]
 - [ resizefs, once-per-instance ]
 - disk_setup
 - mounts
 - set_hostname
 - update_hostname
 - update_etc_hosts
 - ca-certs
 - rsyslog
 - users-groups
 - ssh

# The modules that run in the 'config' stage
cloud_config_modules:
 - ssh-import-id
 - locale
 - set-passwords
 - spacewalk
 - yum-add-repo
 - ntp
 - timezone
 - disable-ec2-metadata
 - runcmd
# - ntp-conf
# - chrony-conf

# The modules that run in the 'final' stage
cloud_final_modules:
 - package-update-upgrade-install
 - puppet
 - chef
 - mcollective
 - salt-minion
 - rightscale_userdata
 - scripts-vendor
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - ssh-authkey-fingerprints
 - keys-to-console
 - phone-home
 - final-message
 - power-state-change

# System and/or distro specific settings
# (not accessible to handlers/transforms)
system_info:
   # This will affect which distro class gets used
   distro: centos
# Other config here will be given to the distro class and/or path classes
   paths:
      cloud_dir: /var/lib/cloud/
      templates_dir: /etc/cloud/templates/
   ssh_svcname: sshd

```

reinstall cloud-init config
```
# The top level settings are used as module
# and base configuration.





# A set of users which may be applied and/or used by various modules
# when a 'default' entry is found it will reference the 'default_user'
# from the distro configuration specified below
users:
   - default


# If this is set, 'root' will not be able to ssh in and they
# will get a message to login instead as the default 
disable_root: false

# This will cause the set+update hostname module to not operate (if true)
preserve_hostname: false

# If you use datasource_list array, keep array items in a single line.
# If you use multi line array, ds-identify script won't read array items.

datasource_list: [ AliYun ]

# Example datasource config
datasource:
    AliYun:
        timeout: 5
        max_wait: 300


# The modules that run in the 'init' stage
cloud_init_modules:
 - migrator
 - seed_random
 - bootcmd
 - write-files
 - [ growpart, once-per-instance ]
 - [ resizefs, once-per-instance ]
 - disk_setup
 - mounts
 - set_hostname
 - update_hostname
 - update_etc_hosts
 - ca-certs
 - rsyslog
 - users-groups
 - ssh

# The modules that run in the 'config' stage
cloud_config_modules:
 - ssh-import-id
 - keyboard
 - locale
 - set-passwords
 - ntp
 - timezone
 - disable-ec2-metadata
 - runcmd

# The modules that run in the 'final' stage
cloud_final_modules:
 - package-update-upgrade-install
 - write-files-deferred
 - puppet
 - chef
 - ansible
 - mcollective
 - salt-minion
 - rightscale_userdata
 - scripts-vendor
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - ssh-authkey-fingerprints
 - keys-to-console
 - phone-home
 - final-message
 - power-state-change

# System and/or distro specific settings
# (not accessible to handlers/transforms)
system_info:
   default_user:
     name: root
     lock_passwd: false
   # This will affect which distro class gets used
   # Unknown/fallback distro.
   distro: ubuntu

```


99_websoft9.cfg
```
timezone: "Asia/Shanghai"

growpart:
  mode: auto
  devices: [/dev/vda2]
  ignore_growroot_disabled: false

runcmd:
  - pvresize /dev/vda2
  - lvextend -l +100%FREE /dev/rootvg/rootlv
  - xfs_growfs /
  - xfs_growfs /dev/rootvg/rootlv
```
