### ISSUE TITLE
rebuild application seems can not support Control startup

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#607]
**Describe the bug**

What is Control startup: https://docs.docker.com/compose/how-tos/startup-order/

```
# image compose and docs: https://hub.docker.com/_/nextcloud

version: '3.8'

services:
  nextcloud:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    ports:
      - ${W9_HTTP_PORT_SET}:80
    volumes:
      - nextcloud:/var/www/html
      - nextcloud-data:/var/www/html/data
    env_file: .env
    environment:
      - MYSQL_PASSWORD=${W9_POWER_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=${W9_ID}-mysql
    depends_on:
      db:
        condition: service_healthy
        restart: true
    restart: unless-stopped

  db:
    image: mysql:${W9_DB_VERSION}
    container_name: ${W9_ID}-mysql
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${W9_POWER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${W9_POWER_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  nextcloud:
  nextcloud-data:
  mysql:

networks:
  default:
    name: ${W9_NETWORK}
    external: true
```
