### ISSUE TITLE
Under what conditions does app install nginx

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#72]
Apps that should not be installed：
1. db
2. bt

**Comment by chendelin1982** [comment]
```
        - name: Check if nginx is necessary
          shell : |
            wget -N https://raw.githubusercontent.com/Websoft9/docker-{{appname}}/main/.env   
            cat .env
          register: env_content
          
  roles:
    - { role: role_common, tags: "role_common" }
    - { role: role_cloud, tags: "role_cloud" }
    - { role: "{{appname}}", tags: "{{appname}}" }
    - { role: role_nginx, tags: "role_nginx", when: env_content.stdout.find('APP_HTTP_PORT') != -1 }
```

solved
