### ISSUE TITLE
Product automation test

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#8]
1. unit test automation 
2. system test automation

**Comment by chendelin1982** [comment]
question to chatGPT: 帮我找一个github action 应用，它可以在阿里云或aws上指定规格和操作系统而创建服务器，然后执行我需要的命令

```
name: 'Terraform GitHub Actions'
on:
  push:
    branches:
    - master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve
```
